spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo
    username: root
    password: 123568

    redis:
      host: 127.0.0.1 # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      timeout: 1000ms # 连接超时时间
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /
#    username: oleyang
#    password: 123568
#    listener:
#      direct:
#        prefetch: 1 # 消息每次只能取一个，然后再处理下一个

server:
  port: 3010

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl